// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UdemyNLayer_Project.Data;

namespace UdemyNLayer_Project.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210819113812_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UdemyNLayer_Project.Core.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "2008 yılından itibaren yazılım teknolojileriyle ilgilenmekteyim. Ağırlıklı olarak .Net teknolojileri üzerine projeler geliştiriyorum. Özel ve Kamu kurumlarına  yazılım eğitimleri  vermekteyim. İkinci üniversite olarak Yönetim Bilişim Sistemleri mezunuyum. Yazılım teknolojileri ilgili her konuyu merak ediyor ve  bilgi sahibi olmaya çalışıyorum. Sıkı bir medium okuyucusuyum. Daha çok üzerinde durduğum teknolojiler; Asp Net Core,Web Api, Azure, Angular,Native Android,Docker, DevOps ... Boş zamanlarımda native android uygulamalar üzerine geliştirmeler yapıyorum. 2017 yılından itibaren Ankarada yaşamaktayım.",
                            Degree = ".Net Developer | Full Stack Developer",
                            Mail = "fatih@gmail.com",
                            Name = "Fatih",
                            Password = "123456",
                            Surname = "Çakıroğlu",
                            TCNo = "12345678910",
                            Telephone = "05424381234"
                        },
                        new
                        {
                            Id = 2,
                            About = "Yazılım Mühendisliği mezunuyum. Udemy'de 14 farklı kursta 60 binden fazla öğrenci (Udemy 1'den fazla kursa kayıtlı öğrencileri tek öğrenci olarak sayıyor) ile 4.72 eğitmen puan ortalaması ile oldukça güzel geri dönüşler alarak eğitim alanında çalışmalarımı sürdürmekteyim.  Profesyonel olarak yazılım alanında projeler yürütmenin yanında aynı zamanda bu alanda eğitmenlik de yapmaktayım. İstanbul'da bulunan ofisimde eğitimler ve proje çalışmalarını bir arada yürüyorum. Üniversite sürecimde İstanbul TeknoPark, Yıldız TeknoPark ve Elazığ TeknoPark'larda bulunan birçok farklı şirkette, alanında lider kıdemli yazılımcılarla beraber projelerde farklı roller üstlenme şansına eriştim.",
                            Degree = "Yazılım Mühendisi ve Eğitmen",
                            Mail = "murat@gmail.com",
                            Name = "Murat",
                            Password = "123456",
                            Surname = "Yücedağ",
                            TCNo = "12345678911",
                            Telephone = "05424381235"
                        },
                        new
                        {
                            Id = 3,
                            About = "Kurslarıma ilgi gösterek beni 2017'de Udemy'nin En İyi 3 Eğitmeni arasına sokan değerli öğrencilerime teşekkürler. Anadolu Üniversitesi - Yönetim Bilişim Sistemleri lisans derecemi tamamlamakla birlikte çeşitli kamu kuruluşlarında edindiğim  11 yıla yakın tecrübenin ardından şu an Bilgi İşlem Yöneticisi olarak profesyonel hayatıma devam etmekteyim.  Ek olarak freelancer ve olarak Web Programlama üzerine aktif olarak çalışarak projeler geliştiriyorum. Son yıllarda çeşitli platformlar üzerinde 400 'den fazla konu üzerine yayınladığım eğitim videoları 2.000.000'u aşan izlenme almış bulunmakta. 2017 itibariyle Udemy'de, kapsayıcı müfredata sahip çeşitli konular üzerine yeni eğitimler üretmeye karar vermiş bulunmaktayım. ",
                            Degree = "Web Geliştirici ve Eğitmen",
                            Mail = "emrah@gmail.com",
                            Name = "Emrah",
                            Password = "123456",
                            Surname = "Yüksel",
                            TCNo = "12345678912",
                            Telephone = "05424381236"
                        },
                        new
                        {
                            Id = 4,
                            About = "Yazılım Danışmanı, Yazılım Mimarı, MCP ve Eğitmen olarak İstanbul, Türkiye'de yaşıyorum. Bilim ve teknolojiye bayılırım. Sektörde çeşitli bilişim firmalarında kıdemli yazılım geliştirici, yazılım mimarı, proje danışmanı ve teknoloji yöneticisi olarak görev yaptım ve yapmaktayım. Kahve kokusu olmadan yapamayan birisiyimdir. Hayatı zevkli yaşamayı sever, sürekli öğrenmeyi ve öğrendiklerimi paylaşmayı hayatıma anlam katan özelliklerim olarak görürüm. ",
                            Degree = "Software Consultant, Software Architect, MCP & Instructor",
                            Mail = "muratBaseren@gmail.com",
                            Name = "Murat ",
                            Password = "123456",
                            Surname = "Baseren",
                            TCNo = "12345678912",
                            Telephone = "05424381236"
                        });
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Geliştirme"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobil Yazılım Geliştirme"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Programlama Dilleri"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oyun Geliştirme"
                        });
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Course_Hour")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Course_ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentsId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Course_Hour = 9.5m,
                            Description = "Uygulamalı Proje Üzerinde OOP (Object Oriented Programming) Kavramlarını Modüler Bir Müfredatla Öğrenin!",
                            InstructorId = 2,
                            Name = "C# İLE OOP TEMELLERİ: ADIM ADIM KATMANLI MİMARİ",
                            Price = 33.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Course_Hour = 45.5m,
                            Description = "ASPNET MVC, Bootstrap, Entity Framework CodeFirst, JQuery(ajax) Kullanarak Visual Studio ile Web Projeleri Geliştirin",
                            InstructorId = 4,
                            Name = "ASP .NET MVC Yazılımcıların Yükselişi",
                            Price = 41.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Course_Hour = 9.5m,
                            Description = "Katmanlı mimari yapısı ile token bazlı kimlik doğrulama/yetkilendirme yapısını inşa etmeyi öğreneceksiniz.",
                            InstructorId = 1,
                            Name = "Asp.Net Core API ( 5.0 ) + Token bazlı kimlik doğrulama(JWT)",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Course_Hour = 13.5m,
                            Description = "BOOTSTRAP en son sürümünü öğrenerek Facebook, Onedio, 140Journos gibi BOOTSTRAP 4 premium tasarımlar yapıyoruz.",
                            InstructorId = 3,
                            Name = "Bootstrap 4 ile Sıfırdan Harika Web Projeleri Oluşturun",
                            Price = 41.99m
                        });
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            OrderTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            OrderTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            OrderTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mail = "beytullah@gmail.com",
                            Name = "Beytullah",
                            Password = "123456",
                            Surname = "Tiryaki",
                            Telephone = "05434382577"
                        },
                        new
                        {
                            Id = 2,
                            Mail = "burak@gmail.com",
                            Name = "Burak",
                            Password = "123456",
                            Surname = "Tiryaki",
                            Telephone = "05434382557"
                        });
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Course", b =>
                {
                    b.HasOne("UdemyNLayer_Project.Core.Models.Category", "Categories")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyNLayer_Project.Core.Instructor", "Instructors")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyNLayer_Project.Core.Models.Student", "Students")
                        .WithMany("Courses")
                        .HasForeignKey("StudentsId");

                    b.Navigation("Categories");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Order", b =>
                {
                    b.HasOne("UdemyNLayer_Project.Core.Models.Course", "Courses")
                        .WithMany("Orders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyNLayer_Project.Core.Models.Student", "Students")
                        .WithMany("Orders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Course", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("UdemyNLayer_Project.Core.Models.Student", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
